-- ===========================================================================
-- DSR Route System — Postgres schema (translated from the original SQLite DDL)
-- ---------------------------------------------------------------------------
-- Notes on the translation:
--   * INTEGER PRIMARY KEY AUTOINCREMENT  -> GENERATED BY DEFAULT AS IDENTITY
--     (BY DEFAULT, not ALWAYS, because the app inserts explicit ids for custom
--      product ids and the data migration preserves original ids).
--   * REAL money columns -> double precision (2-dp rounding stays in JS).
--   * created_at TEXT DEFAULT CURRENT_TIMESTAMP -> timestamptz DEFAULT now().
--   * `date` stays TEXT ('YYYY-MM-DD') so string range filters behave as before.
--   * product_id foreign keys are DEFERRABLE INITIALLY DEFERRED so the
--     "change product id" endpoint can repoint children before the parent PK
--     update inside one transaction.
-- This file is idempotent: safe to run repeatedly.
-- ===========================================================================

CREATE TABLE IF NOT EXISTS profiles (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT NOT NULL,
  current_balance double precision NOT NULL DEFAULT 1250.00
);

-- Hidden buyers stay in the database (and in every report) but drop out of the
-- day-to-day buyer picker. This is the soft alternative to deleting a profile,
-- which is blocked once a buyer has route history.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS hidden boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS products (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT NOT NULL UNIQUE,
  warehouse_stock INTEGER NOT NULL DEFAULT 0,
  unit_price      double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS dsr_sessions (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_id        INTEGER NOT NULL REFERENCES profiles(id),
  date            TEXT NOT NULL,
  prev_balance    double precision NOT NULL,
  total_sales     double precision NOT NULL DEFAULT 0,
  total_payments  double precision NOT NULL DEFAULT 0,
  updated_balance double precision NOT NULL,
  status          TEXT NOT NULL DEFAULT 'IN_PROGRESS'
                    CHECK (status IN ('IN_PROGRESS', 'SETTLED'))
);

CREATE TABLE IF NOT EXISTS dsr_items (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dsr_id        INTEGER NOT NULL REFERENCES dsr_sessions(id) ON DELETE CASCADE,
  product_id    INTEGER NOT NULL REFERENCES products(id)
                  DEFERRABLE INITIALLY DEFERRED,
  opening_stock INTEGER NOT NULL DEFAULT 0,
  loaded_stock  INTEGER NOT NULL DEFAULT 0,
  closing_stock INTEGER NOT NULL DEFAULT 0,
  qty_sold      INTEGER NOT NULL DEFAULT 0,
  unit_price    double precision NOT NULL,
  line_total    double precision NOT NULL DEFAULT 0,
  UNIQUE (dsr_id, product_id)
);

CREATE TABLE IF NOT EXISTS payments (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dsr_id     INTEGER NOT NULL REFERENCES dsr_sessions(id) ON DELETE CASCADE,
  method     TEXT NOT NULL,
  label_info TEXT NOT NULL DEFAULT '',
  amount     double precision NOT NULL CHECK (amount > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS purchases (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id   INTEGER NOT NULL REFERENCES products(id)
                 DEFERRABLE INITIALLY DEFERRED,
  qty_added    INTEGER NOT NULL CHECK (qty_added > 0),
  supplier_ref TEXT NOT NULL DEFAULT '',
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stock_returns (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dsr_id       INTEGER NOT NULL REFERENCES dsr_sessions(id),
  product_id   INTEGER NOT NULL REFERENCES products(id)
                 DEFERRABLE INITIALLY DEFERRED,
  qty_returned INTEGER NOT NULL CHECK (qty_returned > 0),
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- Audit trail of manual warehouse-stock corrections made by an admin (physical
-- count reconciliation, damage write-offs, data-entry fixes).
CREATE TABLE IF NOT EXISTS stock_adjustments (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id)
               DEFERRABLE INITIALLY DEFERRED,
  old_stock  INTEGER NOT NULL,
  new_stock  INTEGER NOT NULL,
  delta      INTEGER NOT NULL,
  mode       TEXT NOT NULL CHECK (mode IN ('set', 'adjust')),
  reason     TEXT NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_adjustments_created_at ON stock_adjustments (created_at);

-- Audit trail of manual ledger-balance corrections made by an admin (opening
-- balance fixes, written-off dues, reconciliation against a paper ledger).
-- A reason is mandatory here, unlike stock corrections: this moves money.
-- profile_id cascades so an admin force-delete of a buyer still succeeds.
CREATE TABLE IF NOT EXISTS balance_adjustments (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id  INTEGER NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  old_balance double precision NOT NULL,
  new_balance double precision NOT NULL,
  delta       double precision NOT NULL,
  mode        TEXT NOT NULL CHECK (mode IN ('set', 'adjust')),
  reason      TEXT NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_balance_adjustments_created_at ON balance_adjustments (created_at);

CREATE INDEX IF NOT EXISTS idx_sessions_buyer_status ON dsr_sessions (buyer_id, status);
CREATE INDEX IF NOT EXISTS idx_sessions_date         ON dsr_sessions (date);
CREATE INDEX IF NOT EXISTS idx_purchases_created_at  ON purchases (created_at);
CREATE INDEX IF NOT EXISTS idx_returns_created_at    ON stock_returns (created_at);

-- ---------------------------------------------------------------------------
-- Seed data (only inserted when the tables are empty). Mirrors the original
-- first-run seed in database.js. Idempotent via ON CONFLICT / WHERE NOT EXISTS.
-- ---------------------------------------------------------------------------
INSERT INTO products (name, warehouse_stock, unit_price)
SELECT * FROM (VALUES
  ('Item A · Beverages', 150, 15.0),
  ('Item B · Snacks',     80, 25.0),
  ('Item C · Dairy',     210, 8.5)
) AS seed(name, warehouse_stock, unit_price)
WHERE NOT EXISTS (SELECT 1 FROM products);

INSERT INTO profiles (name, current_balance)
SELECT * FROM (VALUES
  ('Maya Chen · Route 07',  1250.0),
  ('Jordan Lee · Route 12', 1250.0),
  ('Priya Shah · Route 19', 1250.0)
) AS seed(name, current_balance)
WHERE NOT EXISTS (SELECT 1 FROM profiles);
